<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


function bhus_openhours_feature_opening_hours_instance_load_multiple_alter($results)
{
    $test = 0;
    /*
     * Is the node supposed to be loaded remote ?
     */
    
    /*
     * Fixup the results ?
     */
}
